name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'


      - name: Install dependencies
        run: npm install

      - name: Debug API key
        run: echo "VITE_API_KEY is $VITE_API_KEY"
        env:
          VITE_API_KEY: ${{ secrets.VITE_FONT_API }}
        
      - name: Build
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_FONT_API }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GRID_MENU }}"
          channelId: live
          projectId: grid-menu
